# Generated by Django 4.1.2 on 2022-10-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abies',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
