# Generated by Django 4.1.2 on 2022-10-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_abies_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabCompus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
            ],
        ),
        migrations.CreateModel(
            name='cabDormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
            ],
        ),
    ]
