# Generated by Django 4.1.2 on 2022-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_cabcompus_cabdormitory_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name of Program')),
                ('place', models.CharField(max_length=200, verbose_name='Place of program:')),
                ('description', models.CharField(max_length=200, verbose_name='Abi and Group')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
